volumes:
  postgres_data_local: {}
  postgres_data_local_backups: {}
  redis_data_local: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: 'marcelo_vet/ecommerce_postgres:latest'
    container_name: ecommerce_postgres_local
    restart: always
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_data_local_backups:/backups
    env_file:
      - ./compose/production/postgres/.postgres
    ports:
      - "15432:5432"
  
  redis:
    image: docker.io/redis:6
    volumes:
      - redis_data_local:/data
    ports:
    - "6379:6379"
  
  geoipupdate:
    container_name: geoipupdate
    image: ghcr.io/maxmind/geoipupdate
    restart: always
    env_file:
      - ./compose/production/geoipupdate/.geoipupdate
    volumes:
      - ./backend/app/data:/usr/share/GeoIP